-- Notion → CRM migration: membership, coach, goals, needs
-- Generated from Member_Database CSV
-- Safe to re-run: only updates, no deletes

BEGIN;

UPDATE members SET membership = '6m unlimited', coach = 'Xuan', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'lielle.1999@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'noa.rapaport98@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'haber.mark@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'lui.crispino10@gmail.com';
UPDATE members SET membership = 'Legacy 50', coach = 'Xuan', goals = 'hyrox, lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'gareth.blair@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alexis.sal.gutierrez@gmail.com';
UPDATE members SET membership = '40 Class Pack', coach = 'Andrew', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jay.katzeff@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'santodonatojasmine@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'robynbenay@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', goals = 'consistency', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'avtargill@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'capleo@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'pull up', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'ccfilippelli@icloud.com';
UPDATE members SET membership = 'Legacy 50', coach = 'Andrew', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'nicholas.boisjoli@yahoo.ca';
UPDATE members SET membership = 'EE', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'livia.bsilveira@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'kevin@dubbeldam.ca';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'zanetamaria@hotmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'miriam.gaum@gmail.com';
UPDATE members SET membership = '40 Class Pack', coach = 'Andrew', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'cydneyprusky@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'maddie.shiller@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'evinluan@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Andrew', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'davidmpearl6@gmail.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'marion.godoy@responsivehealth.ca';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'joedacosta18@msn.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'lexielubs@hotmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'kelseyfergus@me.com';
UPDATE members SET membership = '6m prepay', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'renee@recreativeworks.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'cha.jaipaul@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'd.w.king12@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'kristinwalker@live.ca';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'rosanna.sardella@tdsb.on.ca';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'alondra.alicia@yahoo.ca';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'kelly.macdonaldbell@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'evan@thepracticelab.org';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'kara@thepracticelab.org';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'andrewdlang@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'anand33@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'andrew.edward.lopez@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Alvin', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'aldeneakins@gmail.com';
UPDATE members SET membership = '6m prepay', coach = 'Andrew', goals = 'energy', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'gennaro.a.santoro@gmail.com';
UPDATE members SET membership = '8 classes monthly', coach = 'Xuan', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'ainemcglynn+100@gmail.com';
UPDATE members SET membership = 'Class Pack', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'terrakerani@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'stefanomallaci@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'joshua.aaron.hernandez@gmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Xuan', goals = 'energy', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'akurzfeld@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'sherry.pielsticker@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'jason@youxventures.com';
UPDATE members SET membership = 'Legacy 50', coach = 'Andrew', goals = 'pull up', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'avackan@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', goals = 'lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'gelharrar@gmail.com';
UPDATE members SET membership = 'Legacy 50', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'pspencej@gmail.com';
UPDATE members SET membership = '6m prepay', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'brettkarp@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'laineyale@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'roseashleymoss@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'suddenlysafa@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'mr007ward@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'andrewbheppner@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'saulrg.8712@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Andrew', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'jnkoven@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'kennydsmith33@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'jennabfrape@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alyyoung4@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'lalaie@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'szemberg@rogers.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'mishadabhi@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'kateinnis@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', goals = 'lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'elliesings@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'ianmdenomme@gmail.com';
UPDATE members SET membership = 'Legacy 50', coach = 'Xuan', goals = 'lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'danwarrysmith@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'saripapular@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Alvin', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'abbi.kusch@live.ca';
UPDATE members SET membership = 'EE', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'maynardm@look.ca';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'andrea.nuesser@me.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'leslie.kirsh@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'w_wildhaber@hotmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Alvin', goals = 'energy', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'dpswayze@gmail.com';
UPDATE members SET membership = '6m prepay', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'merlene_g@yahoo.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'fatima@quillit.io';
UPDATE members SET membership = '6m unlimited', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'marlissa.flint@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'marleeshinoff@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'howarth.brendan@gmail.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'dara.zarnett@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'karpel.darryl@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'smccabe83@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'saramgreenfield@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'deleojp@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'paul.a.sawtell@gmail.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Xuan', goals = 'lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'francodeleo@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'nguyendave@icloud.com';
UPDATE members SET membership = '3m unlimited', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jacobtbk@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'kate.m.taylor@hotmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'sonya.teece@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'christina.yager@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Alvin', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'oliverchiang0@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Alvin', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'erinlhoops@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Alvin', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alannahhoops@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'cathymartha@gmail.com';
UPDATE members SET membership = '8 classes monthly', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'bettyandveronica2@gmail.com';
UPDATE members SET membership = '8 classes monthly', coach = 'Alvin', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'mdror@bousfields.ca';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'hello@davemurrayillustration.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'elkorchagina@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'toryapearson@gmail.com';
UPDATE members SET membership = '8 classes monthly', coach = 'Linda', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'jordanawarner@gmail.com';
UPDATE members SET membership = 'BT', coach = 'Andrew', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'dbalshine@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'halpern.joanna@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'lucfaig@hotmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'eliefenyes@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alex.kenley@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', goals = 'posture', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'zachcox1@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'judie.damico@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Alvin', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'alisoninwonderland@yahoo.com';
UPDATE members SET membership = 'BT', coach = 'Xuan', goals = 'energy', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'hazel@lioncoffee.ca';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'nayib.rdguez@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'darynjones.mobile@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'forbescampbell@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'katesmason@yahoo.ca';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'rebeccarosecooper@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jlafford@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'gertler@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'rfornarelli@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Alvin', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'camilleis@rogers.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'j.r.mathews@gmail.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Andrew', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'varakini@gmail.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'francisob92@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'rlmelbourne@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'shayna.lp@hotmail.com';
UPDATE members SET membership = 'EE', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jasminechristina2002@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jeremyotto1@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Andrew', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'allie.g.maltz@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'josh_slobodsky@hotmail.com';
UPDATE members SET membership = 'EE', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'july.farfan@hotmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'zahra.ismail@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'melissavasiliev@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'omorra15@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alex@aphillips.ca';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'charise.macdonald@gmail.com';
UPDATE members SET membership = 'BT', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'orsini.mass@gmail.com';
UPDATE members SET membership = '21 day unlimited', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'eborkows@gmail.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'rewati89@gmail.com';
UPDATE members SET membership = 'Legacy 50', coach = 'Xuan', goals = 'lose bf', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'lisa.delcol@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'meltchau@gmail.com';
UPDATE members SET membership = 'BT', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'yvonnejin16@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'brownelee20@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jeremykleynhans@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'tab08270623@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'steroyute@gmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'danielle.riccitiqui@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'vanessa_bellan@hotmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'aliza.shupac@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Alvin', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'georgina.wong@hotmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'amygoldbloom@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alliejanson@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'klhotsky@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'ryan.spinner@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'snooneoc@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jenalyndulnuan@gmail.com';
UPDATE members SET membership = '8 classes monthly', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'rachelsgertler@gmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'karcoorsh@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'herman.danielj@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'jhrho201@gmail.com';
UPDATE members SET membership = 'BT', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'daliabalshine@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'energy', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'retaevelyn2@gmail.com';
UPDATE members SET membership = 'BT', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'avivabalshine@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'sammiskolnik@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'alisonrwmackenzie@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Andrew', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'robertjbaral@gmail.com';
UPDATE members SET membership = '8 classes monthly', coach = 'Linda', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'bove21@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'dfrenkel12@gmail.com';
UPDATE members SET membership = '8 classes monthly', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'lcanonahern@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'vleuten.kayla@gmail.com';
UPDATE members SET membership = 'Legacy 59', goals = 'consistency', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'zachary.n.taylor@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', goals = 'gain muscle', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'zacresnick@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'sarah.bazmi@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Alvin', goals = 'strength', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'jacobs.livy@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Andrew', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'jenna_nightingale@hotmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'im.juliana@gmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Xuan', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'mrhanna@gmail.com';
UPDATE members SET membership = 'Legacy 260', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'szymkoadam@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'shiriner@gmail.com';
UPDATE members SET membership = 'Class Pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'k.filipczuk@gmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'aidenbarcs@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'nahrin.ashour@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'gary.walters1068@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'sarahelainaplummer@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'bradsnow639@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'mandiesfreire@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'joannamorrisonyoga@gmail.com';
UPDATE members SET membership = 'BT', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'tamara.sussman@mcgill.ca';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'andrew.turley2@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'debra.walters75@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'jseftel@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'brandon.isenberg13@gmail.com';
UPDATE members SET membership = 'Prepay 6m', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'kamyar@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'zependypherus@hotmail.com';
UPDATE members SET membership = 'EE', coach = 'Xuan', goals = 'energy', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jeffgoldberg@myyahoo.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'michaela10103@yahoo.ca';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'julia.nefsky@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jonathonsuckonic@gmail.com';
UPDATE members SET membership = '4 classes monthly', coach = 'Linda', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'pode6230@gmail.com';
UPDATE members SET membership = 'Small Group', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'ameistrich@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'katyhuff94@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'marckirshenbaum@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'sadebinns@gmail.com';
UPDATE members SET membership = '3m unlimited', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'michelinemitchell584@gmail.com';
UPDATE members SET membership = '6m unlimited', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'isaac.thornley@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Xuan', goals = 'lose bf', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'ajward89@me.com';
UPDATE members SET membership = '20 pack', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'dan.n.82@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'dmacfed@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'zoewolpert@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'jaysmessages@icloud.com';
UPDATE members SET membership = 'Class Pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'ellie.staniloff95@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'nblackman99@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Xuan', goals = 'strength', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'andrea.furg@gmail.com';
UPDATE members SET coach = 'Xuan', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'alec.barratt@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'ianniciellopriscilla@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'rsbreger@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'sburtex@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'jen.ruddick@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Xuan', goals = 'energy', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'bert.kwon@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'mitchellchippin@gmail.com';
UPDATE members SET membership = 'Legacy 59', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'nick.losacco77@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'sarah.yermus@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'natbookman@gmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'eva.teece.soter@gmail.com';
UPDATE members SET membership = 'EE', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'serious.sam.wins@gmail.com';
UPDATE members SET membership = 'PT', coach = 'Linda', goals = 'strength', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'kgzwick@yahoo.ca';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'hailey.acton@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alifiyahhussain@gmail.com';
UPDATE members SET membership = '5 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'safa.jinje@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'amyemel@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Xuan', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'kjferg87@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'marielalcastro@gmail.com';
UPDATE members SET coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'ambertautkus18@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alon.naomi@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'rhonda.wooddisse@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Andrew', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'davidaaronweisz@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Alvin', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'hava.starkman@gmail.com';
UPDATE members SET membership = '10 pack', needs = 'Med', updated_at = NOW() WHERE LOWER(email) = 'shelbyweber16@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'adiya.poonoosamy13@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'jaynapoonoosamy@gmail.com';
UPDATE members SET coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'erin.delmar@hotmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'territinto@gmail.com';
UPDATE members SET membership = '7 Day Trial', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'rita.francella@me.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'mveli2013@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Alvin', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'joey@vapormusic.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'acrosenstock@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'lucas.bailey8@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'jsilver36@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'megmarshall96@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'tannisrmt@hotmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'lisacristinzo@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'aaron.i.grossman@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'High', updated_at = NOW() WHERE LOWER(email) = 'stefanidis.mary@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', updated_at = NOW() WHERE LOWER(email) = 'stevenlampert1@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'mike.eric12@gmail.com';
UPDATE members SET membership = '1 week unlimited', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'khalili.zand@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'emily.s.alguire@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'elise.meertens@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'fernkachuck@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'melyssa.stein@gmail.com';
UPDATE members SET membership = '10 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'deleojim@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'dougalguire@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'm.factor@sympatico.ca';
UPDATE members SET membership = 'Legacy classes', coach = 'Alvin', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'michelle.factor@icloud.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', goals = 'lose bf', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'mdhcee@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'alter.katy@gmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Xuan', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'duncanembury@gmail.com';
UPDATE members SET membership = '20 pack', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'tiffany_hope@hotmail.com';
UPDATE members SET membership = 'Legacy classes', coach = 'Linda', needs = 'Low', updated_at = NOW() WHERE LOWER(email) = 'sam_abbasi@hotmail.com';

COMMIT;
